name: Push to scratch org and run tests

on:
  push

jobs:
  build:
    uses: ./.github/workflows/test.yml
    with:
      run-tests: yes
    secrets:
      ansible-vault-password: ${{ secrets.VAULT_PASSWORD }}
