name: Push to scratch org and run tests

on:
  pull_request:

jobs:
  build:
    uses: ./test.yml
    with:
      run-tests: yes
    secrets:
      ansible-vault-password: ${{ secrets.VAULT_PASSWORD }}
